---
version: '3.7'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    environment:
      # PUID: 1001
      # PGID: 1001
      TZ: Australia/Sydney
        # - JELLYFIN_PublishedServerUrl=172.16.10.2 #optional
    volumes:
      - config:/config
      - cache:/cache
      - media:/media
    # ports:
      # - 8096:8096
      # - 8920:8920 #optional
      # - 7359:7359/udp #optional
      # - 1900:1900/udp #optional

volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfs.htg.io,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: ":/mnt/disk1/nfs/docker-volumes/jellyfin/config"
  cache:
      driver: local
      driver_opts:
        type: nfs
        o: addr=nfs.htg.io,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
        device: ":/mnt/disk1/nfs/docker-volumes/jellyfin/cache"
  media:
    driver: local
    driver_opts:
      type: none 
      o: bind
      device: "/mnt/disk1/media"

networks:
  default:
    external: true
    name: outside
