version: "3.8"

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer # This line is not allowed to be changed

services:
  nextcloud:
    image: nextcloud/all-in-one:latest-arm64
    restart: always
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed
      - /var/run/docker.sock:/var/run/docker.sock:ro # May be changed on macOS, Windows or docker rootless. See the applicable documentation. If adjusting, don't forget to also set 'DOCKER_SOCKET_PATH'!
    ports:
      # - 80:80 # Can be removed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
      - 8080:8080
      # - 8443:8443 # Can be removed when running behind a reverse proxy. See https://github.com/nextcloud/all-in-one/blob/main/reverse-proxy.md
    environment:
      - APACHE_PORT=11000
      # - SKIP_DOMAIN_VALIDATION=true
      # - APACHE_IP_BINDING=127.0.0.1
      - NEXTCLOUD_DATADIR=/media/sandisk128/nextcloud-aio
      # - NEXTCLOUD_DATADIR=/srv/dev-disk-by-uuid-52682d7c-ef95-463b-a283-0570ad089893/nextcloud-aio
      # - NEXTCLOUD_TRUSTED_CACERTS_DIR=/etc/ssl/certs/openmediavault-69ddbc6f-56f3-49b2-9db7-bffb10395706.crt
# networks:
#   default:
#     external: true
#     name: outside
