---
version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    domainname: htg.io
    restart: unless-stopped
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    ports:
      - '172.16.100.14:53:53/tcp'
      - '172.16.100.14:53:53/udp'
      # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      # - 8088:80/tcp
    environment:
      TZ: 'Australia/Sydney'
      WEBPASSWORD_FILE: /run/secrets/webpassword
      PIHOLE_DNS_: 208.67.222.222;208.67.220.220
      WEBTHEME: default-auto
    secrets:
      - webpassword
    volumes:
      - config:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    # cap_add:
      # - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
secrets:
  webpassword:
    file: /var/lib/docker/volumes/secrets/_data/pihole/webpassword

volumes:
  config:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfs.htg.io,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: ":/mnt/disk1/nfs/docker-volumes/pihole/config"
  dnsmasq:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfs.htg.io,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: ":/mnt/disk1/nfs/docker-volumes/pihole/dnsmasq"

networks:
  default:
    external: true
    name: outside
