---
version: '3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    # privileged: true
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  default:
    external: true
    name: outside

volumes:
    portainer_data:
      external: true
