---
version: '3.7'

secrets:
  secret1:
    file: /var/lib/docker/volumes/secrets/_data/xxxxxx/secret_file.txt

services:
  app-name:
    image:
    container_name:
    hostname:
    restart: unless-stopped
    volumes:
      - data:/data/
    environment:
      ENV_NAME: xxx

    secrets:
      - secret1
    networks:
      - outside
      - backend
    depends_on:
      - dependent-app

volumes:
  data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=nfs.htg.io,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14,nfsvers=4
      device: ":/path/to/storage/folder"

networks:
  backend:
  outside:
    external: true
